---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-gateway
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: gateway
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-alertmanager
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - port: 9093
      protocol: TCP
  podSelector:
    matchLabels:
      app: alertmanager
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-gateway-nats
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gateway
    ports:
    - port: 4222
      protocol: TCP
  podSelector:
    matchLabels:
      app: nats
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-queueworker-nats
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: queue-worker
    ports:
    - port: 4222
      protocol: TCP
  podSelector:
    matchLabels:
      app: nats
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alertmanager-gateway
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: alertmanager
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: gateway
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-alertmanager-prometheus
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: alertmanager
    ports:
    - port: 9090
      protocol: TCP
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
  - Ingress







