---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-grafana-prometheus
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
    - podSelector:
        matchLabels:
          app: grafana
    ports:
    - port: 9090
      protocol: TCP
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-gateway
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: load-balancer
    - podSelector:
        matchLabels:
          app: ingress-controller
    ports:
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app: gateway
  policyTypes:
  - Ingress

